#!/bin/sh

case "$1" in
	start)
		echo -n "Starting hostapd ... "
		rfkill unblock wifi
		start-stop-daemon -S -q -m -b -p /var/run/hostapd.pid --exec /usr/sbin/hostapd -- /etc/hostapd.conf
		echo "done."
		;;
	stop)
		echo -n "Stopping hostapd ..."
		start-stop-daemon -K -q -p /var/run/hostapd.pid
		echo "done."
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac
