################################################################################
#
# linux-deb package generate debian kernel packages
#
################################################################################

LINUX_DEB_SOURCE = linux-deb-0.1.tar.gz
LINUX_DEB_DEPENDENCIES = linux
LINUX_DEB_LICENSE = GPLv2

ifeq ($(BR2_PACKAGE_LINUX_DEB_USE_MAINTAINER_CUSTOM),y)
LINUX_DEB_MAINTAINER_NAME=$(BR2_PACKAGE_LINUX_DEB_MAINTAINER_CUSTOM_NAME)
LINUX_DEB_MAINTAINER_EMAIL=$(BR2_PACKAGE_LINUX_DEB_MAINTAINER_CUSTOM_EMAIL)
BR_NO_CHECK_HASH_FOR += $(RTL8723BS_MP_DRIVER_SOURCE)
else
LINUX_DEB_MAINTAINER_NAME=$(shell git config --get user.name)
LINUX_DEB_MAINTAINER_EMAIL=$(shell git config --get user.email)
endif

ifeq ($(BR2_PACKAGE_LINUX_DEB_USE_CUSTOM_LOCALVERSION),y)
LINUX_DEB_LOCALVERSION=$(BR2_PACKAGE_LINUX_DEB_USE_CUSTOM_LOCALVERSION)
else
LINUX_DEB_LOCALVERSION=$(USER)
endif

LINUX_DEB_INCREMENT=1
LINUX_DEB_PKGVERSION=$(shell make -s -C $(LINUX_DIR) kernelversion)-$(LINUX_DEB_INCREMENT)

LINUX_DEB_MAKE_ENV = \
	$(TARGET_MAKE_ENV) \
	$(LINUX_MAKE_ENV) \
	KBUILD_DEBARCH=armhf \
	LOCALVERSION=-$(LINUX_DEB_LOCALVERSION) \
	KDEB_CHANGELOG_DIST=jessie \
	KDEB_PKGVERSION=$(LINUX_DEB_PKGVERSION) \
	DEBFULLNAME="$(LINUX_DEB_MAINTAINER_NAME)" \
	DEBEMAIL="$(LINUX_DEB_MAINTAINER_EMAIL)"

LINUX_DEB_MAKE_FLAGS = \
	$(LINUX_MAKE_FLAGS)

define LINUX_DEB_BUILD_CMDS
	$(LINUX_DEB_MAKE_ENV) $(MAKE) $(LINUX_DEB_MAKE_FLAGS) -C $(LINUX_DIR) deb-pkg
endef

define LINUX_DEB_INSTALL_TARGET_CMDS
	mv $(BUILD_DIR)/linux*deb $(BINARIES_DIR)
endef

$(eval $(generic-package))
